# docker-compose.yaml
version: '3.8'
services:
  item-service:
    image: item-service
    build:
      context: .
      dockerfile: Dockerfile
      target: item-service
    ports:
      - '50051/tcp'
    deploy:
      resources:
        limits:
          cpus: '0.125'
          memory: 128m
  gateway-service:
    image: gateway-service
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway-service
      args:
        ITEM_SERVICE_ADDRESS: item-service:50051
    ports:
      - '8080:8080'
    deploy:
      resources:
        limits:
          cpus: '0.125'
          memory: 128m